### ISSUE TITLE
The array of people needs to be shuffled before it enters the sorting algorithm

### ISSUE THREAD

**Issue by HannesSam** [UppsalaSystemvetare/Foretagskvallen2020#3]
Då sorteringsalgortimen sorterar uppifrån och ner så ges nu ett försprång till de som anmäler sig först vilket inte stämmer med hur vi hade tänkt det. Så innan listan med användare skickas in i sorteringsalgoritmen skulle den behöva mixas runt så alla hamnar på random platser.

**Comment by jasminealmer** [comment]
fixed
